/**
 * Project taxonomy constants.
 *
 * PROJECT_INDUSTRIES / PROJECT_CATEGORIES are the curated option lists shown
 * in the admin editor (searchable, with free-text custom values allowed).
 * PROJECT_FILTER_GROUPS are the broad, user-facing buckets used on the public
 * Projects page: picking one group automatically matches every related
 * industry and category underneath it.
 */

export const PROJECT_INDUSTRIES = [
  "Accounting & Bookkeeping",
  "Advertising",
  "Aerospace & Defense",
  "Agencies & Studios",
  "Agriculture",
  "AgriTech",
  "AI & Machine Learning",
  "Animation & VFX",
  "Aquaculture",
  "Architecture",
  "Arts & Culture",
  "Automotive",
  "Aviation",
  "Banking",
  "Beauty & Cosmetics",
  "Biotechnology",
  "Blockchain & Crypto",
  "Business Operations",
  "Cafés & Coffee Shops",
  "Call Centers",
  "Capital Markets",
  "Chemicals & Materials",
  "Chiropractic",
  "Civic Tech",
  "Civil Engineering",
  "Climate Tech",
  "Cloud Computing",
  "Communications",
  "Compliance & Risk",
  "Construction",
  "Consulting",
  "Consumer Goods",
  "Contact Centers",
  "Corporate Training",
  "Courier & Parcel Services",
  "Customer Experience",
  "Customer Support",
  "Custom Solutions",
  "Cybersecurity",
  "D2C Brands",
  "Data Analytics",
  "Data Engineering",
  "Dental",
  "Design Agencies",
  "DevOps",
  "Diagnostics & Labs",
  "Distribution & Wholesale",
  "Document Intelligence",
  "Drones & UAV",
  "E-Commerce",
  "E-Learning",
  "EdTech",
  "Education",
  "Elder Care",
  "Electronics & Appliances",
  "Emergency Services",
  "Energy",
  "Engineering Services",
  "Entertainment",
  "Environmental Services",
  "Event Management",
  "Farming & Livestock",
  "Fashion & Apparel",
  "Fertility & Women's Health",
  "Film & Media",
  "Finance & FinTech",
  "Fitness & Wellness",
  "Fleet Management",
  "Food & Beverage",
  "Food Processing",
  "Forestry",
  "Freight & Trucking",
  "Furniture",
  "Gaming",
  "Government",
  "Grocery & Supermarkets",
  "Gyms & Studios",
  "Health & Wellness",
  "Healthcare",
  "HealthTech",
  "Home Improvement",
  "Hospitality",
  "Hospitals & Clinics",
  "Hotels & Resorts",
  "Human Resources",
  "Industrial Automation",
  "Information Technology",
  "Insurance",
  "InsurTech",
  "Interior Design",
  "International Development",
  "Investment & Wealth Management",
  "IoT",
  "Journalism & News",
  "K-12 Schools",
  "Laboratories",
  "Last-Mile Delivery",
  "Law Enforcement",
  "Legal",
  "LegalTech",
  "Lending & Credit",
  "Logistics",
  "Manufacturing",
  "Maritime & Shipping",
  "Marketing",
  "Marketplaces",
  "Media & Publishing",
  "Medical Billing & Coding",
  "Medical Devices",
  "Mental Health",
  "Mining & Metals",
  "Mobile Development",
  "Music & Audio",
  "Natural Resources",
  "Non-Profit",
  "Nonprofit Organizations",
  "Nutrition & Dietetics",
  "Oil & Gas",
  "Optical & Vision Care",
  "Packaging",
  "Payments & Transactions",
  "Payroll & Benefits",
  "Performing Arts",
  "Personal Training",
  "Pets & Animal Care",
  "Pharmaceuticals",
  "Photography",
  "Physiotherapy & Rehabilitation",
  "Podcasting",
  "Professional Services",
  "Property Management",
  "Public Relations",
  "Public Safety",
  "Real Estate",
  "Recycling & Waste Management",
  "RegTech",
  "Renewable Energy",
  "Research & Development",
  "Restaurants & Food Service",
  "Retail",
  "Robotics",
  "SaaS",
  "Sales & CRM",
  "Security & Surveillance",
  "Semiconductor",
  "SEO & SEM",
  "Social Media",
  "Social Services",
  "Solar & Wind Energy",
  "Space & Satellite",
  "Sports",
  "Sports Teams & Leagues",
  "Staffing & Recruitment",
  "Startups",
  "Sustainability & ESG",
  "Tax & Audit",
  "Technology & Software",
  "Telecommunications",
  "Telemedicine",
  "Textiles & Apparel",
  "Tourism",
  "Training & Coaching",
  "Translation & Localization",
  "Transportation",
  "Travel",
  "Universities & Higher Education",
  "Urban Planning",
  "Utilities",
  "Veterinary",
  "Virtual & Augmented Reality",
  "Warehousing & Fulfillment",
  "Water & Sanitation",
  "WealthTech",
  "Web Development",
  "Wellness & Spa",
  "Wholesale",
  "Yoga & Meditation",
] as const;

export type ProjectIndustry = (typeof PROJECT_INDUSTRIES)[number];

export const PROJECT_CATEGORIES = [
  "Accounting Automation",
  "AI Agents & Chatbots",
  "Analytics & Reporting",
  "Backup & Data Sync Automation",
  "Billing & Subscription Management",
  "Booking & Scheduling",
  "Business Operations",
  "Case Management Automation",
  "Claim Processing & Adjudication",
  "Client Portals",
  "Compliance & Audit Automation",
  "Content Generation",
  "Contract Lifecycle Management",
  "CRM Integration",
  "Customer Feedback & Surveys",
  "Customer Support",
  "Data Extraction & OCR",
  "Data Integration & APIs",
  "Data Pipelines & ETL",
  "DevOps & Deployment Automation",
  "Document Digitization & Archival",
  "Document Generation",
  "Document Intelligence",
  "Document Processing",
  "Donor & Fundraising Automation",
  "E-Commerce",
  "Email & SMS Automation",
  "Employee Onboarding & Offboarding",
  "Event Management & Registrations",
  "Expense & Reimbursement Automation",
  "Finance & FinTech",
  "Form Processing & Validation",
  "Grant Management Automation",
  "HR & Recruitment Automation",
  "Internal Tools & Dashboards",
  "Inventory & Order Management",
  "Inventory Forecasting",
  "IT Helpdesk Automation",
  "KYC & Identity Verification",
  "Lead Generation",
  "Lead Scoring & Qualification",
  "LMS & Course Delivery Automation",
  "Location & Geofencing Automation",
  "Logistics",
  "Loyalty & Rewards Automation",
  "Marketing Automation",
  "Media Monitoring & Transcription",
  "Meeting & Calendar Automation",
  "Migration & Data Cleaning",
  "Multi-Channel Integration & Automation",
  "Notification & Alerting",
  "Order Fulfillment Automation",
  "Payment Processing & Reconciliation",
  "Pricing & Quoting Automation",
  "Procurement & Vendor Management",
  "Product Data Management",
  "Project Management Automation",
  "Proposal & RFP Automation",
  "Quality Assurance Automation",
  "Real Estate",
  "Report Generation & Scheduling",
  "Review & Reputation Management",
  "Route & Dispatch Optimization",
  "Sales Automation",
  "Security & Threat Alerting",
  "Shipment Tracking & Notifications",
  "Social Media Automation",
  "Survey & Feedback Collection",
  "Talent Sourcing & Matching",
  "Tenant & Property Management Automation",
  "Timetable & Shift Scheduling",
  "Translation & Localization Automation",
  "Video & Media Processing",
  "Voice & Call Automation",
  "Web Scraping & Data Enrichment",
  "Workflow Automation",
  "Workflow Orchestration",
] as const;

export type ProjectCategory = (typeof PROJECT_CATEGORIES)[number];

export interface ProjectFilterGroup {
  /** Broad, user-facing bucket label shown on the public filter UI. */
  label: string;
  /** Related industries that belong to this bucket. */
  industries: readonly string[];
  /** Related categories that belong to this bucket. */
  categories: readonly string[];
}

export const OTHER_GROUP_LABEL = "Other & Custom";

/**
 * Broad filter buckets used on the public Projects page. Selecting a bucket
 * matches every project whose industry or category is listed underneath it,
 * so the filter UI stays concise while returning comprehensive results.
 */
export const PROJECT_FILTER_GROUPS: readonly ProjectFilterGroup[] = [
  {
    label: "Healthcare & Wellness",
    industries: [
      "Healthcare",
      "HealthTech",
      "Hospitals & Clinics",
      "Medical Devices",
      "Pharmaceuticals",
      "Biotechnology",
      "Dental",
      "Mental Health",
      "Elder Care",
      "Optical & Vision Care",
      "Telemedicine",
      "Diagnostics & Labs",
      "Medical Billing & Coding",
      "Laboratories",
      "Veterinary",
      "Fertility & Women's Health",
      "Chiropractic",
      "Physiotherapy & Rehabilitation",
      "Nutrition & Dietetics",
      "Health & Wellness",
      "Gyms & Studios",
      "Personal Training",
      "Wellness & Spa",
      "Yoga & Meditation",
    ],
    categories: [
      "Booking & Scheduling",
      "Claim Processing & Adjudication",
      "Case Management Automation",
      "KYC & Identity Verification",
      "Document Digitization & Archival",
      "Compliance & Audit Automation",
      "Notification & Alerting",
      "Email & SMS Automation",
      "Loyalty & Rewards Automation",
      "Customer Feedback & Surveys",
      "Timetable & Shift Scheduling",
    ],
  },
  {
    label: "Finance & FinTech",
    industries: [
      "Finance & FinTech",
      "Banking",
      "Investment & Wealth Management",
      "Insurance",
      "Accounting & Bookkeeping",
      "Tax & Audit",
      "Payments & Transactions",
      "Lending & Credit",
      "Capital Markets",
      "RegTech",
      "InsurTech",
      "WealthTech",
    ],
    categories: [
      "Accounting Automation",
      "Payment Processing & Reconciliation",
      "Billing & Subscription Management",
      "Expense & Reimbursement Automation",
      "KYC & Identity Verification",
      "Claim Processing & Adjudication",
      "Compliance & Audit Automation",
      "Analytics & Reporting",
      "Finance & FinTech",
    ],
  },
  {
    label: "Education & Training",
    industries: [
      "Education",
      "E-Learning",
      "EdTech",
      "Training & Coaching",
      "Corporate Training",
      "K-12 Schools",
      "Universities & Higher Education",
    ],
    categories: [
      "LMS & Course Delivery Automation",
      "Form Processing & Validation",
      "Employee Onboarding & Offboarding",
      "Report Generation & Scheduling",
      "Content Generation",
    ],
  },
  {
    label: "E-Commerce & Retail",
    industries: [
      "E-Commerce",
      "Retail",
      "Grocery & Supermarkets",
      "Consumer Goods",
      "Fashion & Apparel",
      "Beauty & Cosmetics",
      "Furniture",
      "Electronics & Appliances",
      "D2C Brands",
      "Marketplaces",
      "Wholesale",
    ],
    categories: [
      "Inventory & Order Management",
      "Order Fulfillment Automation",
      "Inventory Forecasting",
      "Payment Processing & Reconciliation",
      "Loyalty & Rewards Automation",
      "Review & Reputation Management",
      "Email & SMS Automation",
      "Customer Support",
      "Shipment Tracking & Notifications",
      "Product Data Management",
      "Multi-Channel Integration & Automation",
      "E-Commerce",
    ],
  },
  {
    label: "Logistics & Supply Chain",
    industries: [
      "Logistics",
      "Transportation",
      "Fleet Management",
      "Maritime & Shipping",
      "Distribution & Wholesale",
      "Warehousing & Fulfillment",
      "Last-Mile Delivery",
      "Freight & Trucking",
      "Courier & Parcel Services",
    ],
    categories: [
      "Route & Dispatch Optimization",
      "Shipment Tracking & Notifications",
      "Order Fulfillment Automation",
      "Location & Geofencing Automation",
      "Inventory & Order Management",
      "Inventory Forecasting",
      "Document Processing",
      "Compliance & Audit Automation",
      "Logistics",
    ],
  },
  {
    label: "Manufacturing & Industrial",
    industries: [
      "Manufacturing",
      "Industrial Automation",
      "Robotics",
      "Chemicals & Materials",
      "Semiconductor",
      "Textiles & Apparel",
      "Food Processing",
      "Packaging",
      "Mining & Metals",
      "Engineering Services",
      "Automotive",
      "Aerospace & Defense",
    ],
    categories: [
      "Quality Assurance Automation",
      "Procurement & Vendor Management",
      "Compliance & Audit Automation",
      "Inventory & Order Management",
      "Data Pipelines & ETL",
      "Internal Tools & Dashboards",
      "Analytics & Reporting",
      "Backup & Data Sync Automation",
    ],
  },
  {
    label: "Real Estate & Construction",
    industries: [
      "Real Estate",
      "Property Management",
      "Construction",
      "Civil Engineering",
      "Architecture",
      "Interior Design",
      "Urban Planning",
      "Home Improvement",
    ],
    categories: [
      "Tenant & Property Management Automation",
      "Contract Lifecycle Management",
      "Document Digitization & Archival",
      "Document Processing",
      "Form Processing & Validation",
      "Booking & Scheduling",
      "Project Management Automation",
      "Real Estate",
    ],
  },
  {
    label: "Technology & Software",
    industries: [
      "Technology & Software",
      "SaaS",
      "Information Technology",
      "Web Development",
      "Data Analytics",
      "Cybersecurity",
      "IoT",
      "AI & Machine Learning",
      "Cloud Computing",
      "DevOps",
      "Mobile Development",
      "Data Engineering",
      "Blockchain & Crypto",
      "Virtual & Augmented Reality",
      "Space & Satellite",
      "Drones & UAV",
      "Gaming",
      "Startups",
      "Research & Development",
      "Security & Surveillance",
      "Telecommunications",
      "Business Operations",
      "Document Intelligence",
    ],
    categories: [
      "Data Integration & APIs",
      "Data Pipelines & ETL",
      "Internal Tools & Dashboards",
      "Client Portals",
      "Analytics & Reporting",
      "Data Extraction & OCR",
      "Web Scraping & Data Enrichment",
      "DevOps & Deployment Automation",
      "Backup & Data Sync Automation",
      "Security & Threat Alerting",
      "Migration & Data Cleaning",
      "Workflow Orchestration",
      "Workflow Automation",
      "Report Generation & Scheduling",
      "Meeting & Calendar Automation",
      "Business Operations",
    ],
  },
  {
    label: "Marketing & Sales",
    industries: [
      "Marketing",
      "Sales & CRM",
      "Advertising",
      "Public Relations",
      "Social Media",
      "SEO & SEM",
      "Event Management",
      "Agencies & Studios",
      "Communications",
    ],
    categories: [
      "Lead Generation",
      "Lead Scoring & Qualification",
      "Sales Automation",
      "Marketing Automation",
      "CRM Integration",
      "Email & SMS Automation",
      "Social Media Automation",
      "Content Generation",
      "Event Management & Registrations",
      "Review & Reputation Management",
      "Proposal & RFP Automation",
      "Pricing & Quoting Automation",
      "Analytics & Reporting",
      "Location & Geofencing Automation",
    ],
  },
  {
    label: "HR & Recruitment",
    industries: ["Human Resources", "Staffing & Recruitment", "Payroll & Benefits"],
    categories: [
      "HR & Recruitment Automation",
      "Talent Sourcing & Matching",
      "Employee Onboarding & Offboarding",
      "Timetable & Shift Scheduling",
      "Survey & Feedback Collection",
      "Document Processing",
      "Compliance & Audit Automation",
      "Report Generation & Scheduling",
    ],
  },
  {
    label: "Customer Support & CX",
    industries: ["Customer Support", "Customer Experience", "Contact Centers", "Call Centers"],
    categories: [
      "AI Agents & Chatbots",
      "Voice & Call Automation",
      "Customer Support",
      "IT Helpdesk Automation",
      "Customer Feedback & Surveys",
      "Survey & Feedback Collection",
      "Multi-Channel Integration & Automation",
      "Email & SMS Automation",
      "Notification & Alerting",
    ],
  },
  {
    label: "Legal & Professional Services",
    industries: ["Legal", "LegalTech", "Compliance & Risk", "Professional Services", "Consulting"],
    categories: [
      "Contract Lifecycle Management",
      "Document Generation",
      "Document Digitization & Archival",
      "Compliance & Audit Automation",
      "KYC & Identity Verification",
      "Data Extraction & OCR",
      "Case Management Automation",
      "Proposal & RFP Automation",
    ],
  },
  {
    label: "Media, Design & Content",
    industries: [
      "Media & Publishing",
      "Film & Media",
      "Music & Audio",
      "Photography",
      "Design Agencies",
      "Arts & Culture",
      "Performing Arts",
      "Entertainment",
      "Animation & VFX",
      "Journalism & News",
      "Podcasting",
      "Translation & Localization",
    ],
    categories: [
      "Content Generation",
      "Document Generation",
      "Media Monitoring & Transcription",
      "Video & Media Processing",
      "Translation & Localization Automation",
      "Social Media Automation",
      "Document Digitization & Archival",
      "Document Intelligence",
    ],
  },
  {
    label: "Food, Hospitality & Travel",
    industries: [
      "Hospitality",
      "Travel",
      "Restaurants & Food Service",
      "Food & Beverage",
      "Tourism",
      "Hotels & Resorts",
      "Aviation",
      "Cafés & Coffee Shops",
    ],
    categories: [
      "Booking & Scheduling",
      "Loyalty & Rewards Automation",
      "Review & Reputation Management",
      "Event Management & Registrations",
      "Customer Feedback & Surveys",
      "Multi-Channel Integration & Automation",
      "Email & SMS Automation",
    ],
  },
  {
    label: "Government & Non-Profit",
    industries: [
      "Government",
      "Non-Profit",
      "Nonprofit Organizations",
      "Public Safety",
      "Emergency Services",
      "Civic Tech",
      "International Development",
      "Social Services",
      "Law Enforcement",
    ],
    categories: [
      "Case Management Automation",
      "Grant Management Automation",
      "Donor & Fundraising Automation",
      "Form Processing & Validation",
      "Compliance & Audit Automation",
      "Document Digitization & Archival",
      "Report Generation & Scheduling",
      "Notification & Alerting",
      "Survey & Feedback Collection",
    ],
  },
  {
    label: "Energy & Environment",
    industries: [
      "Energy",
      "Renewable Energy",
      "Oil & Gas",
      "Utilities",
      "Environmental Services",
      "Recycling & Waste Management",
      "Water & Sanitation",
      "Sustainability & ESG",
      "Climate Tech",
      "Solar & Wind Energy",
      "Natural Resources",
    ],
    categories: [
      "Analytics & Reporting",
      "Compliance & Audit Automation",
      "Report Generation & Scheduling",
      "Data Pipelines & ETL",
      "Notification & Alerting",
      "Security & Threat Alerting",
    ],
  },
  {
    label: "Sports, Fitness & Wellness",
    industries: ["Sports", "Sports Teams & Leagues", "Fitness & Wellness"],
    categories: [
      "Booking & Scheduling",
      "Timetable & Shift Scheduling",
      "Loyalty & Rewards Automation",
      "Customer Feedback & Surveys",
      "Event Management & Registrations",
    ],
  },
  {
    label: "Agriculture & Food Production",
    industries: [
      "Agriculture",
      "AgriTech",
      "Farming & Livestock",
      "Aquaculture",
      "Forestry",
      "Pets & Animal Care",
    ],
    categories: [
      "Compliance & Audit Automation",
      "Analytics & Reporting",
      "Inventory & Order Management",
      "Report Generation & Scheduling",
      "Data Pipelines & ETL",
      "Location & Geofencing Automation",
    ],
  },
];

/** Returns the filter group that owns the given industry or category value. */
export function getFilterGroupForValue(value: string): ProjectFilterGroup | undefined {
  const normalized = value.trim();
  if (!normalized) return undefined;
  return PROJECT_FILTER_GROUPS.find(
    (g) => g.industries.includes(normalized) || g.categories.includes(normalized),
  );
}

/** True when a project matches a filter group via its industries or category. */
export function projectMatchesGroup(
  group: ProjectFilterGroup,
  industry: readonly string[],
  category: string,
): boolean {
  if (category && group.categories.includes(category)) return true;
  return industry.some((ind) => group.industries.includes(ind));
}

/** True when the project does not belong to any curated filter group. */
export function isUngroupedProject(industry: readonly string[], category: string): boolean {
  return !PROJECT_FILTER_GROUPS.some((g) => projectMatchesGroup(g, industry, category));
}

export const DB_PROJECT_STATUSES = ["draft", "active", "archived"] as const;

export const PUBLIC_PROJECT_STATUSES = [
  "Production Ready",
  "In Development",
  "Prototype",
  "Completed",
] as const;

export const SORT_OPTIONS = [
  { label: "Newest First", value: "created_at_desc" },
  { label: "Oldest First", value: "created_at_asc" },
  { label: "Title A-Z", value: "title_asc" },
  { label: "Title Z-A", value: "title_desc" },
  { label: "Featured First", value: "featured_desc" },
  { label: "Display Order", value: "order_asc" },
] as const;

export type SortOption = (typeof SORT_OPTIONS)[number]["value"];

export const FEATURED_LABELS = {
  featured: "Featured",
  not_featured: "Not Featured",
} as const;

export const PROJECT_DEFAULTS = {
  PAGE_SIZE: 20,
  DEFAULT_SORT: "created_at_desc" as SortOption,
} as const;
