import type { Resource, ResourceCategory, ResourceCollection, ResourceFile } from "@/types/hub";
import type { WorkflowNodeType, WorkflowCategory, WorkflowTemplate } from "@/types/hub";

export const MOCK_RESOURCE_CATEGORIES: ResourceCategory[] = [
  {
    id: "mock-cat-1",
    name: "Templates",
    slug: "templates",
    description: "Ready-to-use automation templates you can copy and adapt.",
    icon: "layout-template",
    display_order: 1,
    status: "published",
    created_at: "2026-07-01T00:00:00.000Z",
    updated_at: "2026-07-01T00:00:00.000Z",
  },
  {
    id: "mock-cat-2",
    name: "AI Agents",
    slug: "ai-agents",
    description: "Configurable AI agent packs for real business workflows.",
    icon: "bot",
    display_order: 2,
    status: "published",
    created_at: "2026-07-01T00:00:00.000Z",
    updated_at: "2026-07-01T00:00:00.000Z",
  },
];

export const MOCK_RESOURCES: Resource[] = [
  {
    id: "mock-res-1",
    type: "workflow",
    title: "Lead Follow-Up Automator",
    slug: "lead-follow-up-automator",
    summary:
      "A two-step n8n workflow that moves new leads from Google Sheets into a CRM and schedules a follow-up email.",
    content: [
      "# Lead Follow-Up Automator",
      "",
      "A small, battle-tested n8n workflow that takes a new lead from a Google Sheet row and:",
      "",
      "1. Creates the contact in your CRM (HubSpot or Pipedrive).",
      "2. Sends a personalized follow-up email.",
      "3. Logs the action back to the sheet.",
      "",
      "## What you need",
      "",
      "- n8n (self-hosted or cloud)",
      "- Google Sheets and Gmail credentials",
      "- A CRM with a public create-contact API",
      "",
      "## Installation",
      "",
      "1. Download the workflow JSON below.",
      "2. In n8n, **Import from File**.",
      "3. Replace the placeholder credentials.",
      "4. Run a test with a sample row.",
      "",
      "> Error handling is built in: failed runs are routed to a dedicated error branch instead of a silent dead-end.",
    ].join("\n"),
    category_id: "mock-cat-1",
    tags: ["n8n", "lead generation", "crm"],
    cover_image: null,
    og_image: null,
    version: "1.0.0",
    changelog: [
      {
        version: "1.0.0",
        date: "2026-07-10",
        notes: ["Initial release."],
      },
    ],
    metadata: { runtime: "n8n", format: "workflow.json" },
    pricing: { model: "free" },
    access_level: "free",
    featured: true,
    display_order: 1,
    status: "published",
    downloads_count: 128,
    seo_title: null,
    seo_description: null,
    canonical_url: null,
    keywords: ["n8n", "leads", "crm"],
    created_at: "2026-07-10T00:00:00.000Z",
    updated_at: "2026-07-10T00:00:00.000Z",
  },
  {
    id: "mock-res-2",
    type: "prompt",
    title: "Client-Onboarding Agent Pack",
    slug: "client-onboarding-agent-pack",
    summary:
      "A set of prompts that turn ChatGPT into a structured client-onboarding assistant for service businesses.",
    content: [
      "# Client-Onboarding Agent Pack",
      "",
      "Five prompts that convert ChatGPT into a reliable onboarding assistant:",
      "",
      "- **Discovery questionnaire** generator",
      "- **Scope and quote** drafter",
      "- **Welcome email** writer",
      "- **Deliverable checklist** builder",
      "- **Kickoff meeting** agenda creator",
      "",
      "Each prompt includes placeholders for your business name, service catalog and tone of voice.",
    ].join("\n"),
    category_id: "mock-cat-2",
    tags: ["chatgpt", "prompts", "onboarding"],
    cover_image: null,
    og_image: null,
    version: "2.1.0",
    changelog: [
      { version: "2.1.0", date: "2026-07-05", notes: ["Added kickoff agenda prompt."] },
      { version: "2.0.0", date: "2026-06-20", notes: ["Reworked quote drafter."] },
    ],
    metadata: { model: "gpt-4o", format: "markdown" },
    pricing: { model: "free" },
    access_level: "free",
    featured: false,
    display_order: 2,
    status: "published",
    downloads_count: 74,
    seo_title: null,
    seo_description: null,
    canonical_url: null,
    keywords: ["prompts", "onboarding", "agents"],
    created_at: "2026-06-20T00:00:00.000Z",
    updated_at: "2026-07-05T00:00:00.000Z",
  },
];

export const MOCK_RESOURCE_FILES: ResourceFile[] = [
  {
    id: "mock-file-1",
    resource_id: "mock-res-1",
    label: "workflow.json",
    description: "n8n import file",
    file_ref: "",
    file_size: 14820,
    file_type: "application/json",
    download_count: 128,
    display_order: 1,
    created_at: "2026-07-10T00:00:00.000Z",
  },
  {
    id: "mock-file-2",
    resource_id: "mock-res-2",
    label: "agent-pack.md",
    description: "Markdown prompt pack",
    file_ref: "",
    file_size: 9214,
    file_type: "text/markdown",
    download_count: 74,
    display_order: 1,
    created_at: "2026-07-05T00:00:00.000Z",
  },
];

export const MOCK_COLLECTIONS: ResourceCollection[] = [
  {
    id: "mock-col-1",
    name: "Getting Started",
    slug: "getting-started",
    description: "The essentials to start automating your business today.",
    cover_image: null,
    featured: true,
    display_order: 1,
    status: "published",
    created_at: "2026-07-01T00:00:00.000Z",
    updated_at: "2026-07-01T00:00:00.000Z",
  },
];

export const MOCK_NODE_TYPES: WorkflowNodeType[] = [
  {
    id: "mock-node-webhook",
    key: "webhook",
    name: "Webhook",
    category: "triggers",
    icon: "zap",
    color: "#f59e0b",
    description: "Starts a workflow when a webhook receives a request.",
    config_schema: { method: { type: "string", required: true } },
    default_config: { method: "POST" },
    display_order: 1,
    status: "published",
    created_at: "2026-07-01T00:00:00.000Z",
    updated_at: "2026-07-01T00:00:00.000Z",
  },
  {
    id: "mock-node-ai",
    key: "ai_generate",
    name: "AI Generate",
    category: "ai",
    icon: "bot",
    color: "#8b5cf6",
    description: "Runs an LLM prompt over the input payload.",
    config_schema: { prompt: { type: "string", required: true } },
    default_config: { prompt: "Summarize the input" },
    display_order: 2,
    status: "published",
    created_at: "2026-07-01T00:00:00.000Z",
    updated_at: "2026-07-01T00:00:00.000Z",
  },
  {
    id: "mock-node-http",
    key: "http_request",
    name: "HTTP Request",
    category: "actions",
    icon: "globe",
    color: "#3b82f6",
    description: "Calls any REST API.",
    config_schema: { url: { type: "string", required: true } },
    default_config: { url: "https://example.com" },
    display_order: 3,
    status: "published",
    created_at: "2026-07-01T00:00:00.000Z",
    updated_at: "2026-07-01T00:00:00.000Z",
  },
];

export const MOCK_WORKFLOW_CATEGORIES: WorkflowCategory[] = [
  {
    id: "mock-wf-cat-1",
    name: "Marketing",
    slug: "marketing",
    description: "Content, campaigns and lead flow.",
    icon: "megaphone",
    display_order: 1,
    status: "published",
    created_at: "2026-07-01T00:00:00.000Z",
    updated_at: "2026-07-01T00:00:00.000Z",
  },
  {
    id: "mock-wf-cat-2",
    name: "Sales",
    slug: "sales",
    description: "Deal flow, follow-up and CRM hygiene.",
    icon: "badge-dollar-sign",
    display_order: 2,
    status: "published",
    created_at: "2026-07-01T00:00:00.000Z",
    updated_at: "2026-07-01T00:00:00.000Z",
  },
];

export const MOCK_TEMPLATES: WorkflowTemplate[] = [
  {
    id: "mock-tpl-1",
    title: "Webhook → AI → Slack",
    slug: "webhook-ai-slack",
    description:
      "Receive a webhook, let AI classify the payload, and post the result to a Slack channel. A perfect first template.",
    category_id: "mock-wf-cat-1",
    difficulty: "beginner",
    tags: ["webhook", "ai", "slack"],
    thumbnail: null,
    nodes: [
      {
        id: "a",
        type: "webhook",
        position: { x: 60, y: 120 },
        config: { method: "POST" },
        label: "Incoming webhook",
      },
      {
        id: "b",
        type: "ai_generate",
        position: { x: 300, y: 120 },
        config: { prompt: "Classify the intent" },
        label: "Classify",
      },
      {
        id: "c",
        type: "http_request",
        position: { x: 540, y: 120 },
        config: { url: "https://hooks.slack.com/..." },
        label: "Post to Slack",
      },
    ],
    edges: [
      { id: "e1", source: "a", target: "b" },
      { id: "e2", source: "b", target: "c" },
    ],
    canvas: {},
    walkthrough: [
      { title: "Trigger", description: "The webhook node waits for an incoming request." },
      { title: "AI", description: "The AI node classifies the payload into an intent." },
      { title: "Notify", description: "The result is posted to your Slack channel." },
    ],
    featured: true,
    display_order: 1,
    status: "published",
    views_count: 412,
    seo_title: null,
    seo_description: null,
    keywords: ["webhook", "slack", "ai"],
    created_at: "2026-07-01T00:00:00.000Z",
    updated_at: "2026-07-01T00:00:00.000Z",
  },
  {
    id: "mock-tpl-2",
    title: "Form → CRM → Follow-up",
    slug: "form-crm-followup",
    description: "Capture form submissions, create a CRM contact and schedule a follow-up task.",
    category_id: "mock-wf-cat-2",
    difficulty: "intermediate",
    tags: ["forms", "crm", "follow-up"],
    thumbnail: null,
    nodes: [
      {
        id: "a",
        type: "webhook",
        position: { x: 60, y: 120 },
        config: { method: "POST" },
        label: "Form webhook",
      },
      {
        id: "b",
        type: "http_request",
        position: { x: 300, y: 120 },
        config: { url: "https://api.crm.com/contacts" },
        label: "Create contact",
      },
    ],
    edges: [{ id: "e1", source: "a", target: "b" }],
    canvas: {},
    walkthrough: [
      { title: "Capture", description: "A form submission hits the webhook." },
      { title: "Enrich", description: "The payload is mapped to your CRM's contact schema." },
    ],
    featured: false,
    display_order: 2,
    status: "published",
    views_count: 231,
    seo_title: null,
    seo_description: null,
    keywords: ["crm", "forms"],
    created_at: "2026-07-01T00:00:00.000Z",
    updated_at: "2026-07-01T00:00:00.000Z",
  },
];
