import type { DbProject } from "@/types/project";

export const MOCK_PROJECTS: DbProject[] = [
  {
    id: "1",
    title: "Fleet Guard",
    slug: "fleet-guard",
    short_description:
      "Real-time AI-powered fleet monitoring system that detects risks, analyzes driver behavior, and alerts teams instantly to prevent incidents.",
    description:
      "A comprehensive AI fleet monitoring system designed for logistics companies. Fleet Guard uses real-time data analysis, AI-powered risk detection, and instant alerting to transform reactive fleet management into a proactive safety system.",
    thumbnail: null,
    images: [],
    video_url: null,
    industry: ["Logistics", "Transportation", "Fleet Management"],
    technologies: ["n8n", "Supabase", "Groq AI", "OpenAI", "React", "Webhooks", "PostgreSQL"],
    category: "Logistics",
    featured: true,
    status: "active",
    order: 1,
    client: null,
    demo_url: null,
    github_url: null,
    seo_title: null,
    seo_description: null,
    og_image: null,
    canonical_url: null,
    keywords: ["fleet monitoring", "AI", "logistics", "safety"],
    challenge:
      "Manual fleet monitoring was reactive, slow, and prone to missed incidents. Dispatchers had to constantly monitor multiple data sources, making it impossible to catch every anomaly or safety concern in real time.",
    solution:
      "An intelligent monitoring layer that connects to existing fleet data sources, analyzes vehicle and driver behaviour using AI, and automatically flags issues — from harsh braking to route deviations — the moment they happen.",
    workflow: [
      "Collects real-time fleet data from GPS, telemetry, and driver inputs",
      "AI analyzes route behaviour, speed patterns, and driving anomalies",
      "Automatically flags incidents, harsh events, and safety risks",
      "Sends instant alerts to dispatchers and management teams",
      "Generates daily safety reports and trend analysis",
    ],
    impact:
      "Transformed a reactive fleet monitoring process into an intelligent, proactive safety system that catches incidents in real time and reduces response times from hours to seconds.",
    created_at: "2024-06-01T00:00:00Z",
    updated_at: "2024-06-01T00:00:00Z",
  },
  {
    id: "2",
    title: "Lease Intelligence System",
    slug: "lease-intelligence",
    short_description:
      "AI-powered lease document analysis system that extracts critical clauses, summaries, and insights from complex real estate lease agreements.",
    description:
      "An intelligent document processing system built for real estate professionals who deal with complex lease agreements. Lease Intelligence automates the extraction of critical lease information from PDFs, providing structured summaries, clause analysis, and instant search across the entire lease portfolio.",
    thumbnail: null,
    images: [],
    video_url: null,
    industry: ["Real Estate", "Legal", "Finance & FinTech"],
    technologies: ["n8n", "Supabase", "OpenAI", "Python", "PostgreSQL", "PDF.js"],
    category: "Real Estate",
    featured: true,
    status: "active",
    order: 2,
    client: null,
    demo_url: null,
    github_url: null,
    seo_title: null,
    seo_description: null,
    og_image: null,
    canonical_url: null,
    keywords: ["lease analysis", "document AI", "real estate", "PDF processing"],
    challenge:
      "Manual lease review was slow, inconsistent, and easy to miss critical clauses. Real estate teams spent hours reading through lengthy PDFs to find specific terms, renewal dates, and financial obligations.",
    solution:
      "A fully automated document intelligence system that processes lease PDFs, extracts key clauses and dates using AI, and generates structured summaries with instant access to every critical detail.",
    workflow: [
      "Upload lease PDF documents",
      "AI extracts key clauses: rent, renewal, termination, escalation",
      "Generates structured summaries with key dates and obligations",
      "Stores and indexes data for instant search across portfolio",
      "Automated alerts for upcoming renewals and deadlines",
    ],
    impact:
      "Reduces manual document review time by 80% and eliminates missed contract details — ensuring real estate teams never miss a critical lease clause again.",
    created_at: "2024-05-01T00:00:00Z",
    updated_at: "2024-05-01T00:00:00Z",
  },
  {
    id: "3",
    title: "Document Intelligence System",
    slug: "document-intelligence",
    short_description:
      "End-to-end automated document processing pipeline that extracts, classifies, validates, and stores business data from any document type.",
    description:
      "A versatile document intelligence pipeline that handles any document type — invoices, contracts, forms, reports — and automatically extracts, classifies, validates, and stores the data. Built for businesses drowning in paperwork who need reliable, scalable document processing automation.",
    thumbnail: null,
    images: [],
    video_url: null,
    industry: ["Document Intelligence", "Business Operations"],
    technologies: ["n8n", "Supabase", "OpenAI", "Python", "PostgreSQL", "Document AI"],
    category: "Document Intelligence",
    featured: true,
    status: "active",
    order: 3,
    client: null,
    demo_url: null,
    github_url: null,
    seo_title: null,
    seo_description: null,
    og_image: null,
    canonical_url: null,
    keywords: ["document processing", "AI extraction", "data pipeline", "automation"],
    challenge:
      "Businesses receive hundreds of documents daily — invoices, contracts, forms — requiring manual sorting, data entry, and validation that is slow, expensive, and error-prone.",
    solution:
      "An intelligent document pipeline that automatically classifies incoming documents, extracts relevant data using AI, validates against business rules, and pushes structured data into the appropriate business systems.",
    workflow: [
      "Auto-classifies documents by type (invoice, contract, form, etc.)",
      "AI extracts structured data fields from each document",
      "Validates extracted data against business rules and thresholds",
      "Routes approved data to ERP, CRM, or accounting systems",
      "Flags exceptions and discrepancies for manual review",
    ],
    impact:
      "Eliminates manual data entry across document-heavy workflows, reducing processing time by 90% and virtually eliminating data entry errors.",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "4",
    title: "Client Onboarding Orchestrator",
    slug: "client-onboarding",
    short_description:
      "Automated client onboarding system that handles intake, verification, document collection, and provisioning across multiple business tools.",
    description:
      "A comprehensive client onboarding automation system that orchestrates the entire new client journey — from initial intake and document collection to account provisioning and welcome communications. Built for service-based businesses that onboard multiple clients weekly.",
    thumbnail: null,
    images: [],
    video_url: null,
    industry: ["Business Operations", "Sales & CRM", "Customer Support"],
    technologies: ["n8n", "Supabase", "Slack API", "Google Workspace", "PostgreSQL"],
    category: "Business Operations",
    featured: true,
    status: "active",
    order: 4,
    client: null,
    demo_url: null,
    github_url: null,
    seo_title: null,
    seo_description: null,
    og_image: null,
    canonical_url: null,
    keywords: ["onboarding", "automation", "client intake", "provisioning"],
    challenge:
      "Manual client onboarding involved 15+ touchpoints across different tools, with coordinators chasing documents, manually creating accounts, and sending follow-ups — resulting in delays and inconsistent experiences.",
    solution:
      "A fully automated onboarding orchestration layer that triggers the entire onboarding sequence from a single intake submission, coordinating across email, CRM, Slack, and business tools without manual intervention.",
    workflow: [
      "Client intake form triggers automated onboarding sequence",
      "Collects and verifies required documents automatically",
      "Provisions accounts across CRM, email, and business tools",
      "Sends personalized welcome communications",
      "Notifies internal teams with onboarding checklist",
    ],
    impact:
      "Reduces onboarding time from days to hours, eliminates manual coordination overhead, and delivers a consistent, professional welcome experience for every new client.",
    created_at: "2024-03-01T00:00:00Z",
    updated_at: "2024-03-01T00:00:00Z",
  },
  {
    id: "5",
    title: "Smart Product Matcher AI",
    slug: "product-matcher",
    short_description:
      "AI-powered product matching system that intelligently matches supplier products with retailer catalogs using semantic understanding.",
    description:
      "An intelligent product matching system that goes beyond simple SKU matching to understand product semantics, attributes, and context. Built for e-commerce businesses that manage multi-supplier catalogs and need to automatically match products across different naming conventions and data formats.",
    thumbnail: null,
    images: [],
    video_url: null,
    industry: ["E-Commerce", "Manufacturing", "Custom Solutions"],
    technologies: ["n8n", "Supabase", "OpenAI", "Python", "PostgreSQL", "Redis"],
    category: "E-Commerce",
    featured: true,
    status: "active",
    order: 5,
    client: null,
    demo_url: null,
    github_url: null,
    seo_title: null,
    seo_description: null,
    og_image: null,
    canonical_url: null,
    keywords: ["product matching", "catalog", "e-commerce", "AI matching"],
    challenge:
      "E-commerce businesses with multi-supplier catalogs struggled to match products across different naming conventions, units, and data formats — requiring hours of manual SKU mapping.",
    solution:
      "An AI-driven matching engine that understands product semantics, compares attributes intelligently, and automatically suggests high-confidence matches between supplier and retailer catalog entries.",
    workflow: [
      "Ingests product catalogs from suppliers and retailers",
      "AI analyzes product names, descriptions, and attributes",
      "Scores and ranks potential matches by confidence level",
      "Auto-accepts high-confidence matches, flags ambiguous ones",
      "Syncs matched products to the master catalog",
    ],
    impact:
      "Dramatically reduces manual SKU mapping effort, enabling e-commerce businesses to onboard new suppliers in hours instead of weeks.",
    created_at: "2024-02-01T00:00:00Z",
    updated_at: "2024-02-01T00:00:00Z",
  },
];
