export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      projects: {
        Row: {
          id: string;
          title: string;
          slug: string;
          short_description: string;
          description: string | null;
          industry: string[] | null;
          category: string;
          technologies: string[] | null;
          thumbnail: string | null;
          images: string[] | null;
          video_url: string | null;
          client: string | null;
          demo_url: string | null;
          github_url: string | null;
          featured: boolean;
          status: string;
          scheduled_for: string | null;
          order: number;
          seo_title: string | null;
          seo_description: string | null;
          keywords: string[] | null;
          og_image: string | null;
          canonical_url: string | null;
          challenge: string | null;
          solution: string | null;
          workflow: string[] | null;
          impact: string | null;
          views: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          short_description?: string;
          description?: string | null;
          industry?: string[] | null;
          category?: string;
          technologies?: string[] | null;
          thumbnail?: string | null;
          images?: string[] | null;
          video_url?: string | null;
          client?: string | null;
          demo_url?: string | null;
          github_url?: string | null;
          featured?: boolean;
          status?: string;
          scheduled_for?: string | null;
          order?: number;
          seo_title?: string | null;
          seo_description?: string | null;
          keywords?: string[] | null;
          og_image?: string | null;
          canonical_url?: string | null;
          challenge?: string | null;
          solution?: string | null;
          workflow?: string[] | null;
          impact?: string | null;
          views?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          short_description?: string;
          description?: string | null;
          industry?: string[] | null;
          category?: string;
          technologies?: string[] | null;
          thumbnail?: string | null;
          images?: string[] | null;
          video_url?: string | null;
          client?: string | null;
          demo_url?: string | null;
          github_url?: string | null;
          featured?: boolean;
          status?: string;
          scheduled_for?: string | null;
          order?: number;
          seo_title?: string | null;
          seo_description?: string | null;
          keywords?: string[] | null;
          og_image?: string | null;
          canonical_url?: string | null;
          challenge?: string | null;
          solution?: string | null;
          workflow?: string[] | null;
          impact?: string | null;
          views?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      case_studies: {
        Row: {
          id: string;
          slug: string;
          title: string;
          subtitle: string;
          challenge: string;
          solution: string;
          workflow: string[] | null;
          impact: string;
          icon: string;
          display_order: number;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          title: string;
          subtitle?: string;
          challenge: string;
          solution: string;
          workflow?: string[] | null;
          impact: string;
          icon?: string;
          display_order?: number;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          title?: string;
          subtitle?: string;
          challenge?: string;
          solution?: string;
          workflow?: string[] | null;
          impact?: string;
          icon?: string;
          display_order?: number;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      content_entries: {
        Row: {
          id: string;
          key: string;
          title: string;
          content: Json;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          title?: string;
          content?: Json;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          title?: string;
          content?: Json;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      seo_metadata: {
        Row: {
          id: string;
          page_key: string;
          title: string;
          description: string | null;
          keywords: string[] | null;
          og_image: string | null;
          canonical_url: string | null;
          robots: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          page_key: string;
          title: string;
          description?: string | null;
          keywords?: string[] | null;
          og_image?: string | null;
          canonical_url?: string | null;
          robots?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          page_key?: string;
          title?: string;
          description?: string | null;
          keywords?: string[] | null;
          og_image?: string | null;
          canonical_url?: string | null;
          robots?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      services: {
        Row: {
          id: string;
          slug: string;
          title: string;
          short_description: string;
          content: Json;
          icon: string;
          featured: boolean;
          display_order: number;
          status: string;
          scheduled_for: string | null;
          seo_title: string | null;
          seo_description: string | null;
          seo_keywords: string[] | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          title: string;
          short_description?: string;
          content?: Json;
          icon?: string;
          featured?: boolean;
          display_order?: number;
          status?: string;
          scheduled_for?: string | null;
          seo_title?: string | null;
          seo_description?: string | null;
          seo_keywords?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          title?: string;
          short_description?: string;
          content?: Json;
          icon?: string;
          featured?: boolean;
          display_order?: number;
          status?: string;
          scheduled_for?: string | null;
          seo_title?: string | null;
          seo_description?: string | null;
          seo_keywords?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      media_files: {
        Row: {
          id: string;
          filename: string;
          original_name: string;
          bucket: string;
          storage_path: string;
          public_url: string | null;
          mime_type: string;
          extension: string;
          size_bytes: number;
          width: number | null;
          height: number | null;
          alt_text: string | null;
          caption: string | null;
          folder: string;
          tags: string[];
          uploaded_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          filename: string;
          original_name: string;
          bucket?: string;
          storage_path: string;
          public_url?: string | null;
          mime_type: string;
          extension: string;
          size_bytes?: number;
          width?: number | null;
          height?: number | null;
          alt_text?: string | null;
          caption?: string | null;
          folder?: string;
          tags?: string[];
          uploaded_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          filename?: string;
          original_name?: string;
          bucket?: string;
          storage_path?: string;
          public_url?: string | null;
          mime_type?: string;
          extension?: string;
          size_bytes?: number;
          width?: number | null;
          height?: number | null;
          alt_text?: string | null;
          caption?: string | null;
          folder?: string;
          tags?: string[];
          uploaded_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      site_settings: {
        Row: {
          id: string;
          site_name: string;
          site_title: string;
          site_description: string;
          tagline: string;
          logo: string | null;
          location: string;
          contact_email: string;
          contact_phone: string | null;
          booking_url: string | null;
          social_github: string | null;
          social_linkedin: string | null;
          social_twitter: string | null;
          social_fiverr: string | null;
          social_instagram: string | null;
          social_youtube: string | null;
          footer_text: string;
          maintenance_mode: boolean;
          show_ai_chat: boolean;
          show_hero: boolean;
          show_showcase: boolean;
          show_services: boolean;
          show_case_studies: boolean;
          show_about: boolean;
          show_testimonials: boolean;
          show_contact: boolean;
          show_blog: boolean;
          show_hub: boolean;
          show_playground: boolean;
          featured_projects_enabled: boolean;
          featured_services_enabled: boolean;
          ga4_measurement_id: string | null;
          gtm_id: string | null;
          clarity_project_id: string | null;
          nav_order: unknown;
          analytics_config: unknown;
          dx_config: unknown;
          monitoring_config: unknown;
          notification_config: unknown;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          site_name?: string;
          site_title?: string;
          site_description?: string;
          tagline?: string;
          logo?: string | null;
          location?: string;
          contact_email?: string;
          contact_phone?: string | null;
          booking_url?: string | null;
          social_github?: string | null;
          social_linkedin?: string | null;
          social_twitter?: string | null;
          social_fiverr?: string | null;
          social_instagram?: string | null;
          social_youtube?: string | null;
          footer_text?: string;
          maintenance_mode?: boolean;
          show_ai_chat?: boolean;
          show_hero?: boolean;
          show_showcase?: boolean;
          show_services?: boolean;
          show_case_studies?: boolean;
          show_about?: boolean;
          show_testimonials?: boolean;
          show_contact?: boolean;
          show_blog?: boolean;
          show_hub?: boolean;
          show_playground?: boolean;
          featured_projects_enabled?: boolean;
          featured_services_enabled?: boolean;
          ga4_measurement_id?: string | null;
          gtm_id?: string | null;
          clarity_project_id?: string | null;
          nav_order?: unknown;
          analytics_config?: unknown;
          dx_config?: unknown;
          monitoring_config?: unknown;
          notification_config?: unknown;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          site_name?: string;
          site_title?: string;
          site_description?: string;
          tagline?: string;
          logo?: string | null;
          location?: string;
          contact_email?: string;
          contact_phone?: string | null;
          booking_url?: string | null;
          social_github?: string | null;
          social_linkedin?: string | null;
          social_twitter?: string | null;
          social_fiverr?: string | null;
          social_instagram?: string | null;
          social_youtube?: string | null;
          footer_text?: string;
          maintenance_mode?: boolean;
          show_ai_chat?: boolean;
          show_hero?: boolean;
          show_showcase?: boolean;
          show_services?: boolean;
          show_case_studies?: boolean;
          show_about?: boolean;
          show_testimonials?: boolean;
          show_contact?: boolean;
          show_blog?: boolean;
          show_hub?: boolean;
          show_playground?: boolean;
          featured_projects_enabled?: boolean;
          featured_services_enabled?: boolean;
          ga4_measurement_id?: string | null;
          gtm_id?: string | null;
          clarity_project_id?: string | null;
          nav_order?: unknown;
          analytics_config?: unknown;
          dx_config?: unknown;
          monitoring_config?: unknown;
          notification_config?: unknown;
          created_at?: string;
          updated_at?: string;
        };
      };
      testimonials: {
        Row: {
          id: string;
          name: string;
          role: string;
          company: string | null;
          quote: string;
          rating: number;
          avatar: string | null;
          display_order: number;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          role?: string;
          company?: string | null;
          quote: string;
          rating?: number;
          avatar?: string | null;
          display_order?: number;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          role?: string;
          company?: string | null;
          quote?: string;
          rating?: number;
          avatar?: string | null;
          display_order?: number;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      leads: {
        Row: {
          id: string;
          name: string;
          email: string;
          phone: string | null;
          message: string | null;
          source: string;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email: string;
          phone?: string | null;
          message?: string | null;
          source?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          phone?: string | null;
          message?: string | null;
          source?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      analytics_events: {
        Row: {
          id: string;
          event: string;
          page_path: string;
          label: string;
          metadata: unknown;
          session_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          event: string;
          page_path?: string;
          label?: string;
          metadata?: unknown;
          session_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          event?: string;
          page_path?: string;
          label?: string;
          metadata?: unknown;
          session_id?: string | null;
          created_at?: string;
        };
      };
      backups: {
        Row: {
          id: string;
          backup_date: string;
          status: string;
          table_count: number;
          file_count: number;
          size_bytes: number;
          manifest: unknown;
          created_at: string;
          updated_at: string;
          source: string;
        };
        Insert: {
          id?: string;
          backup_date: string;
          status?: string;
          table_count?: number;
          file_count?: number;
          size_bytes?: number;
          manifest?: unknown;
          created_at?: string;
          updated_at?: string;
          source?: string;
        };
        Update: {
          id?: string;
          backup_date?: string;
          status?: string;
          table_count?: number;
          file_count?: number;
          size_bytes?: number;
          manifest?: unknown;
          created_at?: string;
          updated_at?: string;
          source?: string;
        };
      };
      health_checks: {
        Row: {
          id: string;
          checked_on: string;
          ok: boolean;
          latency_ms: number | null;
          detail: string;
          created_at: string;
          updated_at: string;
          source: string;
        };
        Insert: {
          id?: string;
          checked_on: string;
          ok?: boolean;
          latency_ms?: number | null;
          detail?: string;
          created_at?: string;
          updated_at?: string;
          source?: string;
        };
        Update: {
          id?: string;
          checked_on?: string;
          ok?: boolean;
          latency_ms?: number | null;
          detail?: string;
          created_at?: string;
          updated_at?: string;
          source?: string;
        };
      };
      notification_deliveries: {
        Row: {
          id: string;
          event: string;
          category: string;
          priority: string;
          title: string;
          message: string;
          channel: string;
          chat_id: string;
          recipient_label: string;
          status: string;
          error: string | null;
          attempts: number;
          created_at: string;
          delivered_at: string | null;
        };
        Insert: {
          id?: string;
          event: string;
          category: string;
          priority?: string;
          title: string;
          message?: string;
          channel?: string;
          chat_id: string;
          recipient_label?: string;
          status?: string;
          error?: string | null;
          attempts?: number;
          created_at?: string;
          delivered_at?: string | null;
        };
        Update: {
          id?: string;
          event?: string;
          category?: string;
          priority?: string;
          title?: string;
          message?: string;
          channel?: string;
          chat_id?: string;
          recipient_label?: string;
          status?: string;
          error?: string | null;
          attempts?: number;
          created_at?: string;
          delivered_at?: string | null;
        };
      };
      blog_posts: {
        Row: {
          id: string;
          title: string;
          slug: string;
          excerpt: string;
          content: string;
          cover_image: string | null;
          categories: string[] | null;
          tags: string[] | null;
          author: string;
          status: string;
          featured: boolean;
          scheduled_for: string | null;
          published_at: string | null;
          seo_title: string | null;
          seo_description: string | null;
          og_image: string | null;
          canonical_url: string | null;
          keywords: string[] | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          excerpt?: string;
          content?: string;
          cover_image?: string | null;
          categories?: string[] | null;
          tags?: string[] | null;
          author?: string;
          status?: string;
          featured?: boolean;
          scheduled_for?: string | null;
          published_at?: string | null;
          seo_title?: string | null;
          seo_description?: string | null;
          og_image?: string | null;
          canonical_url?: string | null;
          keywords?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          excerpt?: string;
          content?: string;
          cover_image?: string | null;
          categories?: string[] | null;
          tags?: string[] | null;
          author?: string;
          status?: string;
          featured?: boolean;
          scheduled_for?: string | null;
          published_at?: string | null;
          seo_title?: string | null;
          seo_description?: string | null;
          og_image?: string | null;
          canonical_url?: string | null;
          keywords?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      resource_categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string;
          icon: string;
          display_order: number;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string;
          icon?: string;
          display_order?: number;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string;
          icon?: string;
          display_order?: number;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      resources: {
        Row: {
          id: string;
          type: string;
          title: string;
          slug: string;
          summary: string;
          content: string;
          category_id: string | null;
          tags: string[];
          cover_image: string | null;
          og_image: string | null;
          version: string | null;
          changelog: unknown;
          metadata: unknown;
          pricing: unknown;
          access_level: string;
          featured: boolean;
          display_order: number;
          status: string;
          downloads_count: number;
          seo_title: string | null;
          seo_description: string | null;
          canonical_url: string | null;
          keywords: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          type: string;
          title: string;
          slug: string;
          summary?: string;
          content?: string;
          category_id?: string | null;
          tags?: string[];
          cover_image?: string | null;
          og_image?: string | null;
          version?: string | null;
          changelog?: unknown;
          metadata?: unknown;
          pricing?: unknown;
          access_level?: string;
          featured?: boolean;
          display_order?: number;
          status?: string;
          downloads_count?: number;
          seo_title?: string | null;
          seo_description?: string | null;
          canonical_url?: string | null;
          keywords?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          type?: string;
          title?: string;
          slug?: string;
          summary?: string;
          content?: string;
          category_id?: string | null;
          tags?: string[];
          cover_image?: string | null;
          og_image?: string | null;
          version?: string | null;
          changelog?: unknown;
          metadata?: unknown;
          pricing?: unknown;
          access_level?: string;
          featured?: boolean;
          display_order?: number;
          status?: string;
          downloads_count?: number;
          seo_title?: string | null;
          seo_description?: string | null;
          canonical_url?: string | null;
          keywords?: string[];
          created_at?: string;
          updated_at?: string;
        };
      };
      resource_files: {
        Row: {
          id: string;
          resource_id: string;
          label: string;
          description: string;
          file_ref: string;
          file_size: number;
          file_type: string;
          download_count: number;
          display_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          resource_id: string;
          label: string;
          description?: string;
          file_ref: string;
          file_size?: number;
          file_type?: string;
          download_count?: number;
          display_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          resource_id?: string;
          label?: string;
          description?: string;
          file_ref?: string;
          file_size?: number;
          file_type?: string;
          download_count?: number;
          display_order?: number;
          created_at?: string;
        };
      };
      resource_collections: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string;
          cover_image: string | null;
          featured: boolean;
          display_order: number;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string;
          cover_image?: string | null;
          featured?: boolean;
          display_order?: number;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string;
          cover_image?: string | null;
          featured?: boolean;
          display_order?: number;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      collection_items: {
        Row: {
          collection_id: string;
          resource_id: string;
          position: number;
        };
        Insert: {
          collection_id: string;
          resource_id: string;
          position?: number;
        };
        Update: {
          collection_id?: string;
          resource_id?: string;
          position?: number;
        };
      };
      workflow_node_types: {
        Row: {
          id: string;
          key: string;
          name: string;
          category: string;
          icon: string;
          color: string;
          description: string;
          config_schema: unknown;
          default_config: unknown;
          display_order: number;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          name: string;
          category?: string;
          icon?: string;
          color?: string;
          description?: string;
          config_schema?: unknown;
          default_config?: unknown;
          display_order?: number;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          name?: string;
          category?: string;
          icon?: string;
          color?: string;
          description?: string;
          config_schema?: unknown;
          default_config?: unknown;
          display_order?: number;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      workflow_categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string;
          icon: string;
          display_order: number;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string;
          icon?: string;
          display_order?: number;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string;
          icon?: string;
          display_order?: number;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      workflow_templates: {
        Row: {
          id: string;
          title: string;
          slug: string;
          description: string;
          category_id: string | null;
          difficulty: string;
          tags: string[];
          thumbnail: string | null;
          nodes: unknown;
          edges: unknown;
          canvas: unknown;
          walkthrough: unknown;
          featured: boolean;
          display_order: number;
          status: string;
          views_count: number;
          seo_title: string | null;
          seo_description: string | null;
          keywords: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          description?: string;
          category_id?: string | null;
          difficulty?: string;
          tags?: string[];
          thumbnail?: string | null;
          nodes?: unknown;
          edges?: unknown;
          canvas?: unknown;
          walkthrough?: unknown;
          featured?: boolean;
          display_order?: number;
          status?: string;
          views_count?: number;
          seo_title?: string | null;
          seo_description?: string | null;
          keywords?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          description?: string;
          category_id?: string | null;
          difficulty?: string;
          tags?: string[];
          thumbnail?: string | null;
          nodes?: unknown;
          edges?: unknown;
          canvas?: unknown;
          walkthrough?: unknown;
          featured?: boolean;
          display_order?: number;
          status?: string;
          views_count?: number;
          seo_title?: string | null;
          seo_description?: string | null;
          keywords?: string[];
          created_at?: string;
          updated_at?: string;
        };
      };
      user_workflows: {
        Row: {
          id: string;
          share_code: string;
          title: string;
          name: string | null;
          email: string | null;
          nodes: unknown;
          edges: unknown;
          canvas: unknown;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          share_code: string;
          title?: string;
          name?: string | null;
          email?: string | null;
          nodes?: unknown;
          edges?: unknown;
          canvas?: unknown;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          share_code?: string;
          title?: string;
          name?: string | null;
          email?: string | null;
          nodes?: unknown;
          edges?: unknown;
          canvas?: unknown;
          created_at?: string;
          updated_at?: string;
        };
      };
      audit_log: {
        Row: {
          id: string;
          action: string;
          entity: string;
          entity_id: string;
          detail: Json;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          action: string;
          entity?: string;
          entity_id?: string;
          detail?: Json;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          action?: string;
          entity?: string;
          entity_id?: string;
          detail?: Json;
          created_by?: string | null;
          created_at?: string;
        };
      };
      content_versions: {
        Row: {
          id: string;
          entity: string;
          entity_id: string;
          version: number;
          data: Json;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          entity: string;
          entity_id: string;
          version: number;
          data: Json;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          entity?: string;
          entity_id?: string;
          version?: number;
          data?: Json;
          created_by?: string | null;
          created_at?: string;
        };
      };
      integration_settings: {
        Row: {
          id: string;
          label: string;
          status: string;
          config: Json;
          expires_at: string | null;
          rotated_at: string | null;
          usage_count: number;
          last_used_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          label: string;
          status?: string;
          config?: Json;
          expires_at?: string | null;
          rotated_at?: string | null;
          usage_count?: number;
          last_used_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          label?: string;
          status?: string;
          config?: Json;
          expires_at?: string | null;
          rotated_at?: string | null;
          usage_count?: number;
          last_used_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      login_history: {
        Row: {
          id: string;
          email: string;
          success: boolean;
          ip: string;
          user_agent: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          success?: boolean;
          ip?: string;
          user_agent?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          success?: boolean;
          ip?: string;
          user_agent?: string;
          created_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
